<a href="https://colab.research.google.com/github/ucchol/docker/blob/main/Data_Mining_Homework_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment /Homework 3

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [3]:
#uploading files
from google.colab import files
uploaded= files.upload()

Saving GrowthData1.csv to GrowthData1.csv
Saving GrowthData2.csv to GrowthData2.csv
Saving Growth-Unknown.csv to Growth-Unknown.csv
Saving JetData.csv to JetData.csv
Saving JetData-unknown.csv to JetData-unknown.csv


# Example DATASET

I have the two files named JetData.csv and JetData-unknown.csv.
JetData.csv has a number of columns, among which Propulsion pressure, Radiation, and Heat are the independent variables. Life span is the dependent variable. The ID column contains just a serial number and does not influence any of the columns.
I performed a linear regression-based analysis to predict the Life span of Jet Engines with IDs X, Y, and Z.
The intercept of the linear regression model turned out to be 1500.0000003813395.
In the regression model, I found that the coefficients with Propulsion pressure, Radiation, and Heat are 3, -8, and -3, respectively. Based on the magnitude of the coefficients, I say that Radiation is the most influential variable for Life span.

In [4]:
df = pd.read_csv("JetData.csv")
df

ID  Propulsion pressure  Radiation        Heat   Life span
0    1             4.221967  29.724798  120.596608  913.077690
1    2             1.862120  42.364783  151.892318  710.991143
2    3            17.682084  35.921981  155.882826  798.021930
3    4             3.238585  34.590306  119.277659  875.160333
4    5             2.340730  40.067117  179.602227  647.678575
5    6            11.547014  19.045088  168.382828  877.131855
6    7            14.111215  25.436550  144.197409  906.249018
7    8             5.015590  45.566745  125.561593  773.828030
8    9            14.067049  29.819593  177.314306  771.701487
9   10             0.935271  23.193977  184.477187  763.822433
10  11             6.910029  27.581581  172.566849  782.376891
11  12            12.007738  32.053936  155.186419  814.032469
12  13            14.960960   9.493303  165.401560  972.731774
13  14             5.110664  33.939592  138.129061  829.428068
14  15             3.879445  13.862940  162.673188  912.715251
15  16             4.120787  23.529849  165.364328  828.030587
16  17            10.858032  28.039071  102.983851  999.309975
17  18             8.875729  26.195735  133.474483  916.637861
18  19             1.741910  26.689716  152.845036  833.172896
19  20            17.725820  26.033975  137.562603  932.217849
20  21            18.204466  40.189193  107.269632  911.290957
21  22            12.620854  14.118024  180.780040  882.578255
22  23            10.632088  41.825448  157.464788  724.898318
23  24            12.101626  38.762457  154.176888  763.674561
24  25            13.985286  19.914663  166.365779  883.541214

# y= 2x+c, where x is the independent variable, y is the dependent variable, and c is the intercept

In [5]:
x = df.values[:, range(1, 4)]  #Propulsion pressure, Radiation, and Heat are the independent variables. 
y = df.values[:, 4]  #Life span is the dependent variable. 

In [6]:
model = LinearRegression().fit(x, y)  #class sklearn.linear_model.LinearRegression(*, fit_intercept=True, copy_X=True, 
                                      #n_jobs=None, positive=False)

In [7]:
print(model.intercept_)  #The intercept of the linear regression model turned out to be 1500.0000003813395.

1500.0000003813393


In [8]:
print(model.coef_) #found that the coefficients with Propulsion pressure, Radiation, and Heat are 3, -8, and -3, respectively. Based on 
                  #the magnitude of the coefficients, I say that Radiation is the most influential variable for Life span.

[ 3. -8. -3.]


I am ranking below the engines of JetData-unknown.csv based on their predicted life span. The one at order 1 has the highest predicted life span.
1. X
2. Z
3. Y

# QUESTION 1

If the coefficient associated with an independent variable column is k, then how will you compute the angle of the associated regression line (model) in degrees? 

# K_angle_degree = Math.Atan(k)*(180/Math.pi)

# QUESTION 5

What is the intercept for the linear regression model using GrowthData2.csv? The error tolerance for this answer is -2.0 to +2.0. That is, your answer will be considered correct if it differs by at most 2.0.

**800.0000001903576**

In [9]:
df2 = pd.read_csv("GrowthData2.csv")
df2

ID   A-Factor   B-Factor    C-Factor   D-Factor   E-Factor  Growth Rate
0      1  12.914732  40.218656  143.736195  45.842464  53.169693  1103.426805
1      2   4.504380  24.303156  173.844537  27.866619  58.520026  1198.142354
2      3   9.292202  45.539439  145.477303  25.761641   6.895694  1304.980555
3      4  11.249013  10.913801  153.936826  30.928504  10.068521  1162.769995
4      5  16.666415  17.009242  113.560090  49.597200  66.335946   843.045246
..   ...        ...        ...         ...        ...        ...          ...
200  201   8.708230  27.835302  136.817074  46.395797  49.490998  1086.237136
201  202   2.264980  16.166851  150.263422  26.714477  16.967128  1241.906489
202  203  15.856586  37.577228  186.177681  35.232066  60.104744  1169.961856
203  204   2.801867  24.076161  121.078324  31.933744  37.687927  1118.457165
204  205   1.001705  10.677583  187.901007  37.210723  31.452036  1302.040191

[205 rows x 7 columns]

In [10]:
x2 = df2.values[:, range(1, 6)]  #A-Factor, B-Factor, C-Factor, D-Factor, and E-Factor are the independent variables. 
y2 = df2.values[:, 6]   #Growth Rate is the dependent variable.

In [11]:
print(x2)

[[ 12.91473238  40.2186559  143.736195    45.84246361  53.16969321]
 [  4.50438025  24.30315641 173.8445367   27.86661898  58.52002626]
 [  9.29220245  45.53943853 145.4773026   25.76164113   6.89569412]
 ...
 [ 15.85658639  37.57722787 186.1776806   35.23206647  60.10474448]
 [  2.80186692  24.07616066 121.0783237   31.93374383  37.6879265 ]
 [  1.00170544  10.67758347 187.9010069   37.21072323  31.45203646]]


In [12]:
print(y2)

[1103.426805  1198.142354  1304.980555  1162.769995   843.0452463
  924.4022831 1172.665006  1154.333731  1124.338159  1159.4018
 1175.209643  1114.873474   795.7162898 1144.101726  1089.25089
  883.2013873  991.3522706 1226.142265  1217.151424   753.1780448
  890.0906105 1122.339875   839.9721989 1143.498619   982.5462052
 1149.353715  1082.624718  1027.1536     956.1186895 1010.906708
 1068.887823   997.2229699  962.4278007  993.5393402 1321.04186
 1195.977926  1319.062087  1164.045328  1182.673823  1238.704772
 1192.242943  1344.64929   1172.489435  1100.97188    961.3663424
 1114.264287  1125.681705  1021.345604  1194.572499  1104.221501
 1123.008095  1111.415949  1147.181033  1144.440646  1072.919538
 1145.626137   950.6720595 1191.290433  1353.575576  1125.851868
 1318.589115  1199.734891  1157.823008  1076.767488  1026.915127
 1061.91069   1181.669022  1154.248119  1080.424933   956.765601
  819.3755877 1117.136425   977.1054333 1215.376102   879.4935286
 1228.963534   806.55049

In [13]:
model_2 = LinearRegression().fit(x2, y2)
print(model_2.intercept_)   #intercept of the model

800.0000001903576


# QUESTION 4

Looking at the coefficients of the model using GrowthData2.csv, order the independent variables based on their strength in influencing the Growth Rate? Place the most influential one first and the least influential one last. If two variables are equally influential to the Growth Rate, in that case, use the column name chronology to order. For example, if Factor-B and Factor-E influence the Growth Rate in equal amounts, then Factor-B should appear before Factor-E.


-
 
A-Factor



-
 
B-Factor



-
 
C-Factor



-
 
D-Factor



-
 
E-Factor



**A--> B--> C--> E--> D**

In [14]:
print(model_2.coef_)  #co-efficient of growthdata2.CSV

[-1.00000000e+01  4.00000000e+00  3.00000000e+00 -4.38021208e-09
 -3.00000000e+00]


In [15]:
print(np.sort(model_2.coef_))

[-1.00000000e+01 -3.00000000e+00 -4.38021208e-09  3.00000000e+00
  4.00000000e+00]


In [16]:
print(np.sort(abs(model_2.coef_))[::-1])

[1.00000000e+01 4.00000000e+00 3.00000000e+00 3.00000000e+00
 4.38021208e-09]


# QUESTION 3

Which column has the least (most negligible) impact on the dependent variable of GrowthData2.csv?

		
A-Factor

		
B-Factor

		
C-Factor

		
D-Factor

		
E-Factor

In [17]:
x2 = df2.values[:, range(1, 6)]  #A-Factor, B-Factor, C-Factor, D-Factor, and E-Factor are the independent variables. 
y2 = df2.values[:, 6]   #Growth Rate is the dependent variable.

In [18]:
print(model_2.coef_)  #co-efficient of growthdata2.CSV

[-1.00000000e+01  4.00000000e+00  3.00000000e+00 -4.38021208e-09
 -3.00000000e+00]


In [19]:
print(np.sort(model_2.coef_))

[-1.00000000e+01 -3.00000000e+00 -4.38021208e-09  3.00000000e+00
  4.00000000e+00]


In [20]:
print(np.sort(abs(model_2.coef_))[::-1])

[1.00000000e+01 4.00000000e+00 3.00000000e+00 3.00000000e+00
 4.38021208e-09]


# QUESTION 2

For which of the variables in GrowthData2.csv, the growth rate decreases with higher values in the respective columns? 

		
A-Factor

		
B-Factor

		
C-Factor

		
D-Factor

		
E-Factor



**A, B, C**

In [22]:
print(np.sort(model_2.coef_))

[-1.00000000e+01 -3.00000000e+00 -4.38021208e-09  3.00000000e+00
  4.00000000e+00]


# Growth-Data1.CSV

# QUESTION 6

Order the samples P, Q, R, S, and T based on their predicted Growth Rates when using the linear regression model of GrowthData1.csv. The sample ID of the highest predicted Growth Rate should appear earliest in the sequence in the ordering. 

In [23]:
df1 = pd.read_csv("GrowthData2.csv")
df1

ID   A-Factor   B-Factor    C-Factor   D-Factor   E-Factor  Growth Rate
0      1  12.914732  40.218656  143.736195  45.842464  53.169693  1103.426805
1      2   4.504380  24.303156  173.844537  27.866619  58.520026  1198.142354
2      3   9.292202  45.539439  145.477303  25.761641   6.895694  1304.980555
3      4  11.249013  10.913801  153.936826  30.928504  10.068521  1162.769995
4      5  16.666415  17.009242  113.560090  49.597200  66.335946   843.045246
..   ...        ...        ...         ...        ...        ...          ...
200  201   8.708230  27.835302  136.817074  46.395797  49.490998  1086.237136
201  202   2.264980  16.166851  150.263422  26.714477  16.967128  1241.906489
202  203  15.856586  37.577228  186.177681  35.232066  60.104744  1169.961856
203  204   2.801867  24.076161  121.078324  31.933744  37.687927  1118.457165
204  205   1.001705  10.677583  187.901007  37.210723  31.452036  1302.040191

[205 rows x 7 columns]

In [24]:
X1 = df1.values[:, range(1, 6)]
y1 = df1.values[:, 6]

In [25]:
model_1 = LinearRegression().fit(X1, y1)

In [26]:
model_1.intercept_

800.0000001903576

In [27]:
print(model_1.coef_)

[-1.00000000e+01  4.00000000e+00  3.00000000e+00 -4.38021208e-09
 -3.00000000e+00]


In [28]:
print(np.sort(abs(model_1.coef_))[::-1])

[1.00000000e+01 4.00000000e+00 3.00000000e+00 3.00000000e+00
 4.38021208e-09]
