<a href="https://colab.research.google.com/github/ucchol/docker/blob/main/Data_Mining_Page_Rank_ALgorithm_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
threshold= 0.0000000000000000001

In [16]:
#adjacency Matrix
A= [[1,1,0], [1,0,1], [0,1,0]]

# A= [[1,1,0], [1,0,1], [0,1,1]]   #spider trap

arr= np.array(A, dtype=float)

s=[]
for i in range(0, len(A)):
  s.append(np.sum(arr[:, i]))

print("Summation of columns: ",s)

Summation of columns:  [2.0, 2.0, 1.0]


In [17]:
#now calculating M, column stochastic Matrix

M= arr
for j in range(0, len(A)):
  M[:,j]= M[:,j]/s[j]
  
print("Column of Stochastic Matrix, M:" )
print(M)

Column of Stochastic Matrix, M:
[[0.5 0.5 0. ]
 [0.5 0.  1. ]
 [0.  0.5 0. ]]


In [20]:
r= (1.0+ np.zeros([len(M), 1]))/ len(M)

print("Initial Rank Vector, r: ")
print(r)

Initial Rank Vector, r: 
[[0.33333333]
 [0.33333333]
 [0.33333333]]


In [25]:
#using while loop

r_prev= r


i=1
while(True):
  print("Interation: ",i)
  r= np.matmul(M, r_prev)
  print("The Rank Vector, r ")
  print(r)
  diff= np.sum(abs(r - r_prev)) #taking L1 norm
  if (diff< threshold):
    break

  r_prev= r 
  i+= 1

print("The final Rank Vector: ")
print(r[:,0])

Streaming output truncated to the last 5000 lines.
The Rank Vector, r 
[[0.13333333 0.13333333 0.13333333]
 [0.13333333 0.13333333 0.13333333]
 [0.06666667 0.06666667 0.06666667]]
Interation:  79041
The Rank Vector, r 
[[0.13333333 0.13333333 0.13333333]
 [0.13333333 0.13333333 0.13333333]
 [0.06666667 0.06666667 0.06666667]]
Interation:  79042
The Rank Vector, r 
[[0.13333333 0.13333333 0.13333333]
 [0.13333333 0.13333333 0.13333333]
 [0.06666667 0.06666667 0.06666667]]
Interation:  79043
The Rank Vector, r 
[[0.13333333 0.13333333 0.13333333]
 [0.13333333 0.13333333 0.13333333]
 [0.06666667 0.06666667 0.06666667]]
Interation:  79044
The Rank Vector, r 
[[0.13333333 0.13333333 0.13333333]
 [0.13333333 0.13333333 0.13333333]
 [0.06666667 0.06666667 0.06666667]]
Interation:  79045
The Rank Vector, r 
[[0.13333333 0.13333333 0.13333333]
 [0.13333333 0.13333333 0.13333333]
 [0.06666667 0.06666667 0.06666667]]
Interation:  79046
The Rank Vector, r 
[[0.13333333 0.13333333 0.13333333]
 [0.1

KeyboardInterrupt: ignored

In [27]:
#using for loop

r_prev= r


i=1
for i in range(1, 1001):
  print("Interation: ",i)
  r= np.matmul(M, r_prev)
  print("The Rank Vector, r ")
  print(r)
  diff= np.sum(abs(r - r_prev)) #taking L1 norm
  if (diff< threshold):
    break

  r_prev= r 
  i+= 1

print("The final Rank Vector: ")
print(r[:,0])

Streaming output truncated to the last 5000 lines.
[[0.13333333 0.13333333 0.13333333]
 [0.13333333 0.13333333 0.13333333]
 [0.06666667 0.06666667 0.06666667]]
Interation:  2
The Rank Vector, r 
[[0.13333333 0.13333333 0.13333333]
 [0.13333333 0.13333333 0.13333333]
 [0.06666667 0.06666667 0.06666667]]
Interation:  3
The Rank Vector, r 
[[0.13333333 0.13333333 0.13333333]
 [0.13333333 0.13333333 0.13333333]
 [0.06666667 0.06666667 0.06666667]]
Interation:  4
The Rank Vector, r 
[[0.13333333 0.13333333 0.13333333]
 [0.13333333 0.13333333 0.13333333]
 [0.06666667 0.06666667 0.06666667]]
Interation:  5
The Rank Vector, r 
[[0.13333333 0.13333333 0.13333333]
 [0.13333333 0.13333333 0.13333333]
 [0.06666667 0.06666667 0.06666667]]
Interation:  6
The Rank Vector, r 
[[0.13333333 0.13333333 0.13333333]
 [0.13333333 0.13333333 0.13333333]
 [0.06666667 0.06666667 0.06666667]]
Interation:  7
The Rank Vector, r 
[[0.13333333 0.13333333 0.13333333]
 [0.13333333 0.13333333 0.13333333]
 [0.06666667 

# RANDOM TELEPORTATION NETWORK

This algorithm heavily depends on the outgoing link. So, it might face the spider trap. We will use random teleportation to solve this problem. So, we have another essential parameter, B= 0.8.

So, the new equation stands: **B*M*r + (1-B)*r*U**, where U is an uniform Martix all elements having the same value(1/3) as we are taking about three websites.

No matter how much we multiply r*U, it will always be U, as the summation o the rank vectors are 1. So, the new equation becomes, **r= B*M*r + (1-B)**

In [35]:
beta= 0.85
uniformR= (1.0- beta)*r
r_prev= r

i=1
for i in range(1, 1001):
  print("Interation: ",i)
  r= beta*np.matmul(M, r_prev)+ uniformR
  print("The Rank Vector, r ")
  print(r)
  diff= np.sum(abs(r - r_prev)) #taking L1 norm
  if (diff< threshold):
    break

  r_prev= r 
  i+= 1

print("The final Rank Vector: ")
print(r[:,0])

Interation:  1
The Rank Vector, r 
[[0.13333333 0.13333333 0.13333333]
 [0.13333333 0.13333333 0.13333333]
 [0.06666667 0.06666667 0.06666667]]
The final Rank Vector: 
[0.13333333 0.13333333 0.06666667]
