<a href="https://colab.research.google.com/github/ucchol/docker/blob/main/Data_Mining_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy.linalg import norm
import pandas as pd
from sklearn.neighbors import NearestNeighbors

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving data-HW1.csv to data-HW1.csv


In [ ]:
import io
df = pd.read_csv(io.BytesIO(uploaded['data-HW1.csv']))

In [ ]:
df

f1   f2   f3        f5        f6        f7        f8       f10  \
0    4.9  2.4  3.3  0.690359  0.422645  0.878143  0.376585  0.362641   
1    6.6  2.9  4.6  0.616655  0.874309  0.459046  0.482676  0.313274   
2    5.2  2.7  3.9  0.437972  0.192906  0.797402  0.240313  0.759578   
3    5.0  2.0  3.5  0.814196  0.597263  0.066628  0.571313  0.433396   
4    5.9  3.0  4.2  0.946941  0.507036  0.769905  0.051230  0.029628   
..   ...  ...  ...       ...       ...       ...       ...       ...   
144  6.9  3.1  4.9  0.231961  0.023425  0.181783  0.424887  0.512870   
145  5.5  2.3  4.0  0.027749  0.881636  0.301138  0.168493  0.851436   
146  6.5  2.8  4.6  0.060429  0.360143  0.251416  0.172121  0.794980   
147  5.7  2.8  4.5  0.881952  0.061499  0.453779  0.754540  0.333308   
148  6.3  3.3  4.7  0.668355  0.238330  0.555170  0.465133  0.951390   

          f11       f12       f13       f14       f15       f16       f23  \
0    0.203020  0.102603  0.076807  0.796171  0.031435  0.335731  0.037298   
1    0.583737  0.973843  0.559280  0.906481  0.624345  0.484077  0.074671   
2    0.132843  0.883097  0.343676  0.113243  0.421582  0.493521  0.132239   
3    0.715804  0.459770  0.828627  0.706856  0.463386  0.211002  0.069390   
4    0.871120  0.931087  0.663233  0.320440  0.268052  0.936505  0.588667   
..        ...       ...       ...       ...       ...       ...       ...   
144  0.483258  0.283802  0.004491  0.085795  0.779293  0.519107  0.305918   
145  0.891328  0.851857  0.026040  0.881096  0.250410  0.946801  0.031899   
146  0.480263  0.108190  0.205383  0.488929  0.928787  0.084804  0.313312   
147  0.690532  0.671305  0.723592  0.844107  0.530368  0.900918  0.068293   
148  0.940967  0.169391  0.389159  0.526002  0.278094  0.289880  0.038466   

          f24       f25  f26  
0    0.967632  0.143654  1.0  
1    0.340242  0.545620  1.3  
2    0.784557  0.168092  1.4  
3    0.317207  0.782985  1.0  
4    0.320596  0.898933  1.5  
..        ...       ...  ...  
144  0.193924  0.995627  1.5  
145  0.127452  0.780047  1.3  
146  0.638242  0.557372  1.5  
147  0.624383  0.508832  1.3  
148  0.836724  0.435064  1.6  

[149 rows x 18 columns]

In [ ]:
print("Row 0: ", np.array(df.iloc[0]))
print("\n")
print("Row 1: ", np.array(df.iloc[1]))

Row 0:  [4.9        2.4        3.3        0.6903594  0.4226447  0.87814319
 0.37658528 0.36264095 0.20301953 0.10260258 0.07680687 0.79617099
 0.03143519 0.33573081 0.03729804 0.9676317  0.14365367 1.        ]


Row 1:  [6.6        2.9        4.6        0.61665504 0.8743091  0.45904553
 0.48267602 0.31327391 0.58373695 0.97384314 0.55928033 0.90648114
 0.62434542 0.4840768  0.07467125 0.34024186 0.54561987 1.3       ]


In [ ]:
#cosine similarity

def cosine(v1, v2):
  n= np.dot(v1,v2)
  d= np.sqrt(sum(v1**2)) * np.sqrt(sum(v2**2))
  c= n/d
  return c

co= cosine(df.iloc[0], df.iloc[1])
print("cosine Similarity: ",co)

cosine Similarity:  0.9796454701665941


In [ ]:
#jaccard similarity

def jaccard(v1,v2):
  minimus=[]
  maximus=[]

  for i in range(0, len(v1)):
    minimus.append(min(v1[i], v2[i]))
    maximus.append(max(v1[i], v2[i]))

  j= sum(minimus)/sum(maximus)
  return j

jd= jaccard(df.iloc[0], df.iloc[1])
print("Jaccard Similarity: ",jd)

Jaccard Similarity:  0.6495937402532462


In [ ]:
#tanimoto similarity

def tanimoto(v1, v2):
  n= np.dot(v1,v2)
  d= (np.sqrt(sum(v1**2)))**2 + (np.sqrt(sum(v2**2)))**2 - n
  c= n/d
  return c

tn= tanimoto(df.iloc[0], df.iloc[1])
print("tanimoto Similarity: ",tn)

tanimoto Similarity:  0.8883294479993544


In [ ]:
#eucledean distance

def euclid(v1,v2):
  e= np.sqrt(sum((v1-v2)**2))
  return e

ed= euclid(df.iloc[0], df.iloc[1])
print("Eucledean Distance: ", ed)

Eucledean Distance:  2.71990142706248


In [ ]:
#manhattan distance

def manhattan(v1, v2):
  m= sum(abs(v1-v2))
  return m

md= manhattan(df.iloc[0], df.iloc[1])
print("Manhattan: ", md)

Manhattan:  8.552651256999999


In [ ]:
#reference vector for KNN

refInd= 10 #reference vector
refVec= df.iloc[refInd]
k=5 #number of neighbors

In [ ]:
#model for nearest neighbor using euclidean

nbrs= NearestNeighbors(n_neighbors= k, algorithm= "brute", metric= "euclidean" ) #for metric we can't accept Jaccard as knn is expecting a distance
fitted= nbrs.fit(df)
distances, indices= fitted.kneighbors([refVec])
print("indices of the nearest neighbors; ")
print(indices)
print("distances of the nearest neighbors; ")
print(distances)

indices of the nearest neighbors; 
[[10  9  7 17 12]]
distances of the nearest neighbors; 
[[8.42936970e-08 1.36099141e+00 1.54569261e+00 1.54949591e+00
  1.54992765e+00]]


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(


In [ ]:
#model for nearest neighbor using manhattan

nbrs= NearestNeighbors(n_neighbors= k, algorithm= "brute", metric= "manhattan" ) #for metric we can't accept Jaccard as knn is expecting a distance
fitted= nbrs.fit(df)
distances, indices= fitted.kneighbors([refVec])
print("indices of the nearest neighbors; ")
print(indices)
print("distances of the nearest neighbors; ")
print(distances)

indices of the nearest neighbors; 
[[10  9 17 15 12]]
distances of the nearest neighbors; 
[[0.         5.01643507 5.05932368 5.40795824 5.44569167]]


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(


In [ ]:
#reference vector for KNN

refInd= 10 #reference vector
refVec= df.iloc[refInd]
k=5 #number of neighbors

In [ ]:
#model for nearest neighbor using Jaccard
#for metric we can't accept Jaccard as knn is expecting a distance
nbrs=NearestNeighbors(n_neighbors=k,algorithm='brute',metric=lambda a, b: 1 - jaccard(a, b))
fitted= nbrs.fit(df)
distances, indices= fitted.kneighbors([refVec])
print("indices of the nearest neighbors: ")
print(indices)
print("distances of the nearest neighbors: ")
print(distances)

indices of the nearest neighbors: 
[[ 10  17  15   9 147]]
distances of the nearest neighbors: 
[[0.         0.21081411 0.22612156 0.22615242 0.23078577]]


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(


**QUESTION 5**

What is the Euclidean distance between rows 50 and 55?

In [ ]:
#eucledean distance

def euclid(v1,v2):
  e= np.sqrt(sum((v1-v2)**2))
  return e

ed= euclid(df.iloc[50], df.iloc[55])
print("Eucledean Distance: ", ed)

Eucledean Distance:  1.9729823248531622


**QUESTION 7**

What is the Jaccard similarity between rows 111 and 101?

In [ ]:
#jaccard similarity

def jaccard(v1,v2):
  minimus=[]
  maximus=[]

  for i in range(0, len(v1)):
    minimus.append(min(v1[i], v2[i]))
    maximus.append(max(v1[i], v2[i]))

  j= sum(minimus)/sum(maximus)
  return j

jd= jaccard(df.iloc[111], df.iloc[101])
print("Jaccard Similarity: ",jd)

Jaccard Similarity:  0.7441790855335985


**QUESTION 8**

What is the cosine similarity between rows 35 and 99?

In [ ]:
#cosine similarity

def cosine(v1, v2):
  n= np.dot(v1,v2)
  d= np.sqrt(sum(v1**2)) * np.sqrt(sum(v2**2))
  c= n/d
  return c

co= cosine(df.iloc[35], df.iloc[99])
print("cosine Similarity: ",co)

cosine Similarity:  0.9100554389849032


**QUESTION 1**

What is the Tanimoto similarity between rows 3 and 102?

In [ ]:
#tanimoto similarity

def tanimoto(v1, v2):
  n= np.dot(v1,v2)
  d= (np.sqrt(sum(v1**2)))**2 + (np.sqrt(sum(v2**2)))**2 - n
  c= n/d
  return c

tn= tanimoto(df.iloc[3], df.iloc[102])
print("tanimoto Similarity: ",tn)

tanimoto Similarity:  0.7974743328062395


**QUESTION 3**

The first nearest neighbor of a row is itself. Which row is the second nearest neighbor of row 101 using euclidean distance?

In [ ]:
#reference vector for KNN

refInd= 101 #reference vector
refVec= df.iloc[refInd]
k=5 #number of neighbors

#model for nearest neighbor using eucledean

nbrs= NearestNeighbors(n_neighbors= k, algorithm= "brute", metric= "euclidean" ) #for metric we can't accept Jaccard as knn is expecting a distance
fitted= nbrs.fit(df)
distances, indices= fitted.kneighbors([refVec])
print("indices of the nearest neighbors; ")
print(indices)
print("distances of the nearest neighbors; ")
print(distances)

indices of the nearest neighbors; 
[[101 122 132 129 127]]
distances of the nearest neighbors; 
[[0.         1.21469392 1.2157888  1.22386318 1.32038255]]


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(


**QUESTION 6**

The first nearest neighbor of a row is itself. Which of the following statements is/are correct? 

		
The second nearest neighbor of row 63 using Euclidean distance is the same as the second nearest neighbor of row 63 using Manhattan distance.

		
The fourth nearest neighbor of row 21 using Euclidean distance is the same as the fourth nearest neighbor of row 21 using Manhattan distance.

		
The third nearest neighbor of row 63 using Euclidean distance is the same as the third nearest neighbor of row 63 using Manhattan distance.

		
The fifth nearest neighbor of row 21 using Euclidean distance is the same as the fifth nearest neighbor of row 21 using Manhattan distance.

In [ ]:
#option 1 and 3: euclidean distance
#The second nearest neighbor of row 63 using Euclidean distance 
#is the same as the second nearest neighbor of row 63 using Manhattan distance.

#reference vector for KNN

refInd= 63 #reference vector
refVec= df.iloc[refInd]
k=5 #number of neighbors

#model for nearest neighbor using eucledean

nbrs= NearestNeighbors(n_neighbors= k, algorithm= "brute", metric= "euclidean" ) #for metric we can't accept Jaccard as knn is expecting a distance
fitted= nbrs.fit(df)
distances, indices= fitted.kneighbors([refVec])
print("indices of the nearest neighbors using euclidean: ")
print(indices)
print("distances of the nearest neighbors; ")
print(distances)

print("*******************************************************************************************************")
#option 1 and 3: manhattan distance
#The second nearest neighbor of row 63 using Euclidean distance 
#is the same as the second nearest neighbor of row 63 using Manhattan distance.

refInd= 63 #reference vector
refVec= df.iloc[refInd]
k=5 #number of neighbors

#model for nearest neighbor using eucledean

nbrs= NearestNeighbors(n_neighbors= k, algorithm= "brute", metric= "manhattan" ) #for metric we can't accept Jaccard as knn is expecting a distance
fitted= nbrs.fit(df)
distances, indices= fitted.kneighbors([refVec])
print("indices of the nearest neighbors using Manhattan: ")
print(indices)
print("distances of the nearest neighbors; ")
print(distances)



indices of the nearest neighbors using euclidean: 
[[63 83 79 45 86]]
distances of the nearest neighbors; 
[[0.         1.19949819 1.22548933 1.32094813 1.32325672]]
*******************************************************************************************************
indices of the nearest neighbors using Manhattan: 
[[63 83 52 86 79]]
distances of the nearest neighbors; 
[[0.         4.06445342 4.34817859 4.37387373 4.46802224]]


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(


**Option 1: This option is true as the second neighbour in both case in 83.**
**Option 3: This option is wrong as one is 79, and other is 52.**

In [ ]:
#option 2
#The fourth nearest neighbor of row 21 using Euclidean distance 
#is the same as the fourth nearest neighbor of row 21 using Manhattan distance.

#reference vector for KNN

refInd= 21 #reference vector
refVec= df.iloc[refInd]
k=5 #number of neighbors

#model for nearest neighbor using eucledean

nbrs= NearestNeighbors(n_neighbors= k, algorithm= "brute", metric= "euclidean" ) #for metric we can't accept Jaccard as knn is expecting a distance
fitted= nbrs.fit(df)
distances, indices= fitted.kneighbors([refVec])
print("indices of the nearest neighbors using euclidean: ")
print(indices)
print("distances of the nearest neighbors; ")
print(distances)

print("*******************************************************************************************************")
#option 1: manhattan distance
#The second nearest neighbor of row 63 using Euclidean distance 
#is the same as the second nearest neighbor of row 63 using Manhattan distance.

#model for nearest neighbor using eucledean

nbrs= NearestNeighbors(n_neighbors= k, algorithm= "brute", metric= "manhattan" ) #for metric we can't accept Jaccard as knn is expecting a distance
fitted= nbrs.fit(df)
distances, indices= fitted.kneighbors([refVec])
print("indices of the nearest neighbors using Manhattan: ")
print(indices)
print("distances of the nearest neighbors; ")
print(distances)

indices of the nearest neighbors using euclidean: 
[[21 28 39  1 40]]
distances of the nearest neighbors; 
[[1.68587394e-07 1.14860116e+00 1.18647510e+00 1.23710635e+00
  1.26397079e+00]]
*******************************************************************************************************
indices of the nearest neighbors using Manhattan: 
[[21 28 39 27 40]]
distances of the nearest neighbors; 
[[0.         3.72412972 4.18166674 4.18812899 4.43135326]]


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(


The 4th Neighbor is different(1 and 27)

Option 4: this is true as both is 40 



**QUESTION 2**

When you use Jaccard disssimilarity for finding k-nearest neighbors, which row index has the second nearest neighbor of the row with index 105? Write only an integer. Writing anything else other than an integer will result in zero points for this question.

In [ ]:
#option 2
#The fourth nearest neighbor of row 21 using Euclidean distance 
#is the same as the fourth nearest neighbor of row 21 using Manhattan distance.

#reference vector for KNN

refInd= 21 #reference vector
refVec= df.iloc[refInd]
k=5 #number of neighbors

#model for nearest neighbor using eucledean

nbrs= NearestNeighbors(n_neighbors= k, algorithm= "brute", metric= "euclidean" ) #for metric we can't accept Jaccard as knn is expecting a distance
fitted= nbrs.fit(df)
distances, indices= fitted.kneighbors([refVec])
print("indices of the nearest neighbors using euclidean: ")
print(indices)
print("distances of the nearest neighbors; ")
print(distances)

print("*******************************************************************************************************")
#option 1: manhattan distance
#The second nearest neighbor of row 63 using Euclidean distance 
#is the same as the second nearest neighbor of row 63 using Manhattan distance.

#model for nearest neighbor using eucledean

nbrs= NearestNeighbors(n_neighbors= k, algorithm= "brute", metric= "manhattan" ) #for metric we can't accept Jaccard as knn is expecting a distance
fitted= nbrs.fit(df)
distances, indices= fitted.kneighbors([refVec])
print("indices of the nearest neighbors using Manhattan: ")
print(indices)
print("distances of the nearest neighbors; ")
print(distances)

indices of the nearest neighbors using euclidean: 
[[21 28 39  1 40]]
distances of the nearest neighbors; 
[[1.68587394e-07 1.14860116e+00 1.18647510e+00 1.23710635e+00
  1.26397079e+00]]
*******************************************************************************************************
indices of the nearest neighbors using Manhattan: 
[[21 28 39 27 40]]
distances of the nearest neighbors; 
[[0.         3.72412972 4.18166674 4.18812899 4.43135326]]


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(


In [ ]:
#reference vector for KNN

refInd= 105 #reference vector
refVec= df.iloc[refInd]
k=5 #number of neighbors

#model for nearest neighbor using Jaccard
#for metric we can't accept Jaccard as knn is expecting a distance
nbrs=NearestNeighbors(n_neighbors=k,algorithm='brute',metric=lambda a, b: 1 - jaccard(a, b))
fitted= nbrs.fit(df)
distances, indices= fitted.kneighbors([refVec])
print("indices of the nearest neighbors; ")
print(indices)
print("distances of the nearest neighbors; ")
print(distances)

indices of the nearest neighbors; 
[[105 139 130 109  94]]
distances of the nearest neighbors; 
[[0.         0.1878111  0.23854946 0.2546017  0.25913402]]


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(
