<a href="https://colab.research.google.com/github/ucchol/docker/blob/Data-Mining/Data_Mining_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support

In [ ]:
from google.colab import files
uploaded= files.upload()

Saving 16189299.txt to 16189299.txt
Saving pecan yield.txt to pecan yield.txt
Saving pecan.txt to pecan.txt
Saving Pecan-TestDataForClassification.csv to Pecan-TestDataForClassification.csv
Saving Pecan-ForClassification.csv to Pecan-ForClassification.csv


In [ ]:
df= pd.read_csv("Pecan-ForClassification.csv")

In [ ]:
X= df.values[:, range(1, 4)]
y= df.values[:, 4]

In [ ]:
model= LogisticRegression().fit(X, y)

In [8]:
tdf= pd.read_csv("Pecan-TestDataForClassification.csv")

In [9]:
testData= tdf.values[:, range(1, 4)]

In [10]:
pred= model.predict(testData)

In [11]:
#should be 30 labels as tdf has 30 labels
pred

array([1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0.])

In [12]:
predprobaMatrix= model.predict_proba(testData)

In [13]:
predprobaMatrix

array([[1.51981434e-08, 9.99999985e-01],
       [1.75120330e-08, 9.99999982e-01],
       [9.87468735e-01, 1.25312646e-02],
       [6.25011154e-12, 1.00000000e+00],
       [1.12841599e-02, 9.88715840e-01],
       [7.99258493e-09, 9.99999992e-01],
       [3.59073176e-08, 9.99999964e-01],
       [9.99996065e-01, 3.93483768e-06],
       [1.26296057e-07, 9.99999874e-01],
       [5.03752595e-12, 1.00000000e+00],
       [9.99997187e-01, 2.81260362e-06],
       [9.99994071e-01, 5.92859995e-06],
       [3.34994127e-05, 9.99966501e-01],
       [9.96132198e-01, 3.86780190e-03],
       [2.06452633e-11, 1.00000000e+00],
       [5.10799266e-07, 9.99999489e-01],
       [3.09530179e-13, 1.00000000e+00],
       [2.99410909e-05, 9.99970059e-01],
       [2.60593054e-02, 9.73940695e-01],
       [4.36717329e-11, 1.00000000e+00],
       [9.40855702e-01, 5.91442979e-02],
       [9.96492330e-01, 3.50767048e-03],
       [4.18047067e-03, 9.95819529e-01],
       [4.42312853e-13, 1.00000000e+00],
       [9.927875

In [14]:
model.coef_

array([[ 0.36171669, -0.81967238,  0.2113815 ]])

In [15]:
model.intercept_

array([-10.62540993])

# Evaluation

In [16]:
model.score(X, y)

1.0

In [21]:
y_actual= tdf.values[:, 4]
y_actual

array([1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0.])

In [22]:
confusion_matrix(y_actual, pred)

array([[11,  0],
       [ 0, 19]])

In [23]:
precision_recall_fscore_support(y_actual, pred)

(array([1., 1.]), array([1., 1.]), array([1., 1.]), array([11, 19]))

New Data

In [24]:
y_true= ["cat", "dog", "cat", "bird", "dog"]
y_pr= ["cat", "cat", "cat", "bird", "dog"]

In [25]:
precision_recall_fscore_support(y_true, y_pr, labels=["cat", "bird", "dog"])

(array([0.66666667, 1.        , 1.        ]),
 array([1. , 1. , 0.5]),
 array([0.8       , 1.        , 0.66666667]),
 array([2, 1, 2]))