<a href="https://colab.research.google.com/github/ucchol/docker/blob/Data-Mining/Data_Mining_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score 
from sklearn.metrics import silhouette_samples 
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import DBSCAN

In [2]:
from google.colab import files
uploaded = files.upload()

Saving dry_beans_benchmarkclusters.csv to dry_beans_benchmarkclusters.csv
Saving dry_beans_data.csv to dry_beans_data.csv


In [3]:
#csv data read

dryBean_data = pd.read_csv('dry_beans_data.csv')
dryBean_goldset = pd.read_csv('dry_beans_benchmarkclusters.csv', header=None)

In [6]:
dryBean_data.shape

(13611, 16)

In [7]:
dryBean_goldset.shape

(13611, 1)

In [4]:
data_dryBean = dryBean_data.values

In [8]:
#goldset

labels = dryBean_data.values
gld_labels = labels[:, 0] 
print(gld_labels.shape)
print(gld_labels)

(13611,)
[ 50833.  30727.  41324. ...  36741. 191554.  60409.]


#K-Means Clustering

In [11]:
k=3
km = KMeans(n_clusters=k, verbose=1).fit(data_dryBean)

/usr/local/lib/python3.8/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Initialization complete
Iteration 0, inertia 3581674585045.666.
Iteration 1, inertia 2569967482872.9106.
Iteration 2, inertia 2522420961915.582.
Iteration 3, inertia 2512539412831.802.
Iteration 4, inertia 2509990089302.9194.
Iteration 5, inertia 2509157267608.3545.
Iteration 6, inertia 2508990131428.292.
Converged at iteration 6: center shift 4177.851567081078 within tolerance 10914.86670982776.
Initialization complete
Iteration 0, inertia 2562068496311.4746.
Iteration 1, inertia 2509428656027.384.
Iteration 2, inertia 2509046408263.8154.
Iteration 3, inertia 2508974265034.165.
Converged at iteration 3: center shift 1504.7459941953316 within tolerance 10914.86670982776.
Initialization complete
Iteration 0, inertia 3462307536314.2627.
Iteration 1, inertia 2553531501656.3027.
Iteration 2, inertia 2515821127177.801.
Iteration 3, inertia 2510685937875.7227.
Iteration 4, inertia 2509259276654.2744.
Iteration 5, inertia 2509055783948.1064.
Converged at iteration 5: center shift 9512.1798681

In [12]:
print("The clustering Assignments are: ")
print(km.labels_)

The clustering Assignments are: 
[0 0 0 ... 0 1 2]


In [13]:
#sum of squared distance

print("SSD (sum of squared distance): ", km.inertia_)

SSD (sum of squared distance):  2508967708931.4937


In [16]:
def rand_index(result, gf):
  print(len(result))
  print(len(gf))
  count_matches = 0.0
  count_all = 0.0
  for i in range(len(result)):
    for j in range(i+1, len(gf)):
      if (result[i] == result[j] and gf[i] == gf[j]) or (result[i] != result[j] and gf[i] != gf[j]):
        count_matches += 1
      count_all += 1
  return count_matches / count_all

goldLabels = gld_labels
kLabels = km.labels_
print("Rand Index: ", rand_index(kLabels, goldLabels))

13611
13611
Rand Index:  0.44969755035082865


In [25]:
#purity in K-means clustering

def purity(result, gs):   #result and gs are labels
  cLabel= list(set(result)) # list will have the cluster labels
  gLabel= list(set(gs)) # list will have the ground_cluster truth labels , length of t from our equation
  n= len(result)
  k= len(cLabel)
  t= len(gLabel)

  #constructing dictionaries for cLable and glabel
  cLabelsD= dict(zip(cLabel, range(k))) #for clustering
  gLabelsD= dict(zip(gLabel, range(t))) #for ground truth

  clusterGroundDistr= [[0] * t for i in range(k)] #this will create a 2D array of t many columns and k many rows

  for i in range(n):  #number of elements we have is n
    clusterIndex = cLabelsD[result[i]]
    groundIndex = gLabelsD[gs[i]]
    clusterGroundDistr[clusterIndex][groundIndex] += 1

  p=0 # p is purity
  for i in range(k):
    p += max(clusterGroundDistr[i])

  return p/n

print(purity(gld_labels, km.labels_ ))

0.9998530600249798


#Agglomerative clustering

In [15]:
agg = AgglomerativeClustering(n_clusters=3).fit(dryBean_data)
agg.labels_

array([0, 2, 2, ..., 2, 1, 0])

In [19]:
#Rand index using agglomerative clustering 

print(rand_index(gld_labels, agg.labels_))

13611
13611
0.5129810671459004


In [26]:
#Purity using Agglomerative clustering 

print(purity(gld_labels, agg.labels_ ))

0.9997061200499596


# DBSCAN

In [23]:
dbres = DBSCAN(eps=1.0, min_samples=3).fit(data_dryBean)
print(dbres.labels_)

[-1 -1 -1 ... -1 -1 -1]


In [24]:
dbres = DBSCAN(eps=1.0, min_samples=5).fit(data_dryBean)
print(dbres.labels_)

[-1 -1 -1 ... -1 -1 -1]


#Question 1

What is the average silhouette coefficient of the result retrieved by the agglomerative clustering algorithm with k=7? Your result must be correct up to two digits after the decimal point. Use default values with n_clusters=7 for scikitlearn AgglomerativeClustering. That is, do not mention any linkage in the parameters so that the default one is used.

In [27]:
#agglomerative clustering algorithm with k=7

agg = AgglomerativeClustering(n_clusters=7).fit(dryBean_data)
agg.labels_

array([0, 4, 1, ..., 1, 5, 0])

In [28]:
print(silhouette_score(data_dryBean, agg.labels_))

0.5050234057202192


#Question 2

What is the number of outlier data points if you apply DBSCAN with eps= 50.0  and min_pts= 12? You must enter an integer only. 

In [30]:
dbres_dry1 = DBSCAN(eps=50, min_samples=12).fit(dryBean_data)
print(dbres_dry1.labels_)

[-1 -1 44 ... 14 -1 -1]


In [31]:
unique, counts = np.unique(dbres_dry1.labels_, return_counts=True)
print(np.asarray((unique, counts)).T)

[[  -1 9894]
 [   0   99]
 [   1   67]
 [   2   26]
 [   3  141]
 [   4   20]
 [   5   19]
 [   6   44]
 [   7   68]
 [   8   13]
 [   9   30]
 [  10   31]
 [  11  104]
 [  12   69]
 [  13   24]
 [  14   81]
 [  15   36]
 [  16  109]
 [  17   61]
 [  18   83]
 [  19   35]
 [  20   70]
 [  21   18]
 [  22   58]
 [  23  100]
 [  24  105]
 [  25   14]
 [  26   37]
 [  27   52]
 [  28   46]
 [  29   36]
 [  30   21]
 [  31   69]
 [  32   56]
 [  33   17]
 [  34   65]
 [  35   26]
 [  36   61]
 [  37   15]
 [  38   40]
 [  39   40]
 [  40   64]
 [  41   37]
 [  42   56]
 [  43   58]
 [  44   27]
 [  45   27]
 [  46   22]
 [  47   40]
 [  48   38]
 [  49   12]
 [  50   26]
 [  51   20]
 [  52   23]
 [  53   30]
 [  54   26]
 [  55   17]
 [  56   30]
 [  57   20]
 [  58   17]
 [  59   40]
 [  60   22]
 [  61   23]
 [  62   49]
 [  63   12]
 [  64   14]
 [  65   26]
 [  66   12]
 [  67   23]
 [  68   28]
 [  69   17]
 [  70   18]
 [  71   18]
 [  72   26]
 [  73   58]
 [  74   15]
 [  75   26]

#Question 3

What is the number of outlier data points if you apply DBSCAN with eps= 20.0  and min_pts= 5? You must enter an integer only. 

In [32]:
dbres_dry1 = DBSCAN(eps=20, min_samples=5).fit(dryBean_data)
print(dbres_dry1.labels_)

[-1 -1 -1 ... -1 -1 -1]


In [33]:
unique, counts = np.unique(dbres_dry1.labels_, return_counts=True)
print(np.asarray((unique, counts)).T)

[[   -1 13321]
 [    0     5]
 [    1     5]
 [    2     8]
 [    3     7]
 [    4     6]
 [    5     8]
 [    6     5]
 [    7     6]
 [    8     8]
 [    9     5]
 [   10     6]
 [   11     7]
 [   12     5]
 [   13     7]
 [   14     5]
 [   15     5]
 [   16     9]
 [   17     5]
 [   18     5]
 [   19     5]
 [   20    11]
 [   21     5]
 [   22     6]
 [   23     7]
 [   24     6]
 [   25     5]
 [   26     5]
 [   27     6]
 [   28     8]
 [   29     6]
 [   30     5]
 [   31     8]
 [   32     8]
 [   33     5]
 [   34     6]
 [   35     5]
 [   36     5]
 [   37     5]
 [   38     5]
 [   39     6]
 [   40     3]
 [   41     5]
 [   42     5]
 [   43     7]
 [   44     5]
 [   45     5]
 [   46     5]
 [   47     5]
 [   48     5]]


#Question 4

What is the size of the largest cluster using the agglomerative clustering algorithm with k=7? (That is, how many data points are there in the largest cluster when you apply the agglomerative clustering algorithm with k=7?) Use default values with n_clusters=7 for scikitlearn AgglomerativeClustering. That is, do not mention any linkage in the parameters so that the default one is used. Write only an integer.

In [34]:
agg = AgglomerativeClustering(n_clusters=7).fit(dryBean_data)
agg.labels_

array([0, 4, 1, ..., 1, 5, 0])

In [35]:
unique, counts = np.unique(agg.labels_, return_counts=True)
print(np.asarray((unique, counts)).T)

[[   0 2881]
 [   1 4939]
 [   2  335]
 [   3  979]
 [   4 3069]
 [   5  185]
 [   6 1223]]


#Question 5

Consider that you have a dataset that comes with groung truth labels. The ground truth labels have seven clusters, 0 to 6. You run k-means with k=8. The k-means outcome labels vary between 0 to 7. You find that data points with ground truth labels from 0 to 5 match exactly your k-means outcome. Cluster 6 of ground truth is split between cluster labels 6 and 7 of the k-means outcome.

For this data scenerio, which of the following statements is/are CORRECT?

		
The Rand index is less than zero.

		
The Rand index is exactly 1.0.

		
**The Purity score is exactly 1.0.**

		
Rand index is higher than the purity score.

		
Purity score and Rand index are equal.

		
Purity score is less than 0.

#Question 6

What is the purity if you run k-means with k=7? Your answer must be correct up to two digits after the decimal point. You might have to run k-means many times to find the best result. (Remember, k-means is non-deterministic.)

In [49]:
k=7
km = KMeans(n_clusters=k, verbose=1).fit(data_dryBean)

/usr/local/lib/python3.8/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Initialization complete
Iteration 0, inertia 777993565823.852.
Iteration 1, inertia 686232342046.5693.
Iteration 2, inertia 657022282773.5596.
Iteration 3, inertia 640202480564.0181.
Iteration 4, inertia 630458217753.4067.
Iteration 5, inertia 626709307173.1357.
Iteration 6, inertia 624188731547.0562.
Iteration 7, inertia 622369027840.2556.
Iteration 8, inertia 620935040743.9001.
Iteration 9, inertia 619803194616.877.
Iteration 10, inertia 619006453596.2808.
Iteration 11, inertia 618364671973.4335.
Iteration 12, inertia 617737456298.6086.
Iteration 13, inertia 617336115844.6404.
Iteration 14, inertia 617089566021.9901.
Iteration 15, inertia 616909478405.8768.
Iteration 16, inertia 616742544700.2769.
Iteration 17, inertia 616576059231.5859.
Iteration 18, inertia 616375949113.1426.
Iteration 19, inertia 616178804983.0668.
Iteration 20, inertia 616034177921.4028.
Iteration 21, inertia 615927409253.9226.
Iteration 22, inertia 615881616728.446.
Iteration 23, inertia 615824631191.4628.
Itera

In [51]:
#purity in K-means clustering

def purity(result, gs):   #result and gs are labels
  cLabel= list(set(result)) # list will have the cluster labels
  gLabel= list(set(gs)) # list will have the ground_cluster truth labels , length of t from our equation
  n= len(result)
  k= len(cLabel)
  t= len(gLabel)

  #constructing dictionaries for cLable and glabel
  cLabelsD= dict(zip(cLabel, range(k))) #for clustering
  gLabelsD= dict(zip(gLabel, range(t))) #for ground truth

  clusterGroundDistr= [[0] * t for i in range(k)] #this will create a 2D array of t many columns and k many rows

  for i in range(n):  #number of elements we have is n
    clusterIndex = cLabelsD[result[i]]
    groundIndex = gLabelsD[gs[i]]
    clusterGroundDistr[clusterIndex][groundIndex] += 1

  p=0 # p is purity
  for i in range(k):
    p += max(clusterGroundDistr[i])

  return p/n

print(purity(gld_labels, km.labels_ ))

0.9995591800749394


#Question 7

How many data points are there in the dry beans dataset?

In [40]:
dryBean_data.shape

(13611, 16)

#Question 8

After applying k-means clustering with k=7, how many objects/data points are there in the smallest cluster?

In [52]:
k=7
km = KMeans(n_clusters=k, verbose=1).fit(data_dryBean)

/usr/local/lib/python3.8/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Initialization complete
Iteration 0, inertia 854464663998.2454.
Iteration 1, inertia 707814492099.384.
Iteration 2, inertia 662813790297.158.
Iteration 3, inertia 637649758202.3743.
Iteration 4, inertia 624880678228.7856.
Iteration 5, inertia 619609999306.2307.
Iteration 6, inertia 617167760275.7744.
Iteration 7, inertia 616044254722.499.
Iteration 8, inertia 615516476755.0981.
Iteration 9, inertia 615338236765.2463.
Iteration 10, inertia 615237250156.1519.
Iteration 11, inertia 615165326780.944.
Converged at iteration 11: center shift 8879.506415891175 within tolerance 10914.86670982776.
Initialization complete
Iteration 0, inertia 936451246332.0222.
Iteration 1, inertia 857469131762.7654.
Iteration 2, inertia 855245697245.928.
Iteration 3, inertia 854289941383.2584.
Iteration 4, inertia 853686773685.2395.
Iteration 5, inertia 853285832727.0173.
Iteration 6, inertia 853064544484.7523.
Iteration 7, inertia 852889713349.462.
Iteration 8, inertia 852737322551.8505.
Iteration 9, inertia 8

In [53]:
unique, counts = np.unique(km.labels_, return_counts=True)
n= print(np.asarray((unique, counts)).T)

[[   0 3262]
 [   1  217]
 [   2 1160]
 [   3 2529]
 [   4  303]
 [   5 1917]
 [   6 4223]]


#Question 9

How many dimensional dataset is the Dry Beans dataset? (How many features are there in the dry_beans_data.csv file?) Just write an integer. 

In [43]:
dryBean_data.shape

(13611, 16)

#Question 10

Among three clustering algorihms -- kmeans, agglomerative, and DBSCAN -- which one(s) might give several different Rand Index values in multiple executions with the same data and parameters.

Why? Answer in one or two sentences.

The k-means clustering algorithm might give different Rand Index values in multiple executions with the same data and parameters because it is sensitive to the initial random selection of cluster centroids. The DBSCAN algorithm is less likely to produce different Rand Index values as it is based on density and does not rely on initializations, while the agglomerative clustering algorithm's behavior depends on the linkage criterion chosen.

#Question 11

What is the purity if you run agglomerative clustering with k=7? Your answer must be correct up to two digits after the decimal point. Use default values with n_clusters=7 for scikitlearn AgglomerativeClustering. That is, do not mention any linkage in the parameters so that the default one is used.

In [54]:
agg = AgglomerativeClustering(n_clusters=7).fit(dryBean_data)
agg.labels_

array([0, 4, 1, ..., 1, 5, 0])

In [55]:
#Purity using Agglomerative clustering 

print(purity(gld_labels, agg.labels_ ))

0.9989714201748585


#Question 12

What is the average silhouette coefficient of the result retrieved by the k-means algorithm with k=7? Your result must be correct up to two digits after the decimal point. You might have to run k-means several times to find the best result. (Remember, k-means is non-deterministic.)

In [56]:
k=7
km = KMeans(n_clusters=k, verbose=1).fit(data_dryBean)

/usr/local/lib/python3.8/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


Initialization complete
Iteration 0, inertia 974038613993.9314.
Iteration 1, inertia 858003451336.8033.
Iteration 2, inertia 813117292133.1132.
Iteration 3, inertia 786980034838.7477.
Iteration 4, inertia 770602310726.6241.
Iteration 5, inertia 758294448963.7515.
Iteration 6, inertia 748339712578.5028.
Iteration 7, inertia 740258580003.7804.
Iteration 8, inertia 734896625243.9478.
Iteration 9, inertia 731248016000.0651.
Iteration 10, inertia 729189489735.6133.
Iteration 11, inertia 727713204007.052.
Iteration 12, inertia 726217604897.832.
Iteration 13, inertia 725052276269.0758.
Iteration 14, inertia 724241859329.926.
Iteration 15, inertia 723655544025.0316.
Iteration 16, inertia 723238572241.4592.
Iteration 17, inertia 722868169594.6364.
Iteration 18, inertia 722356247912.7302.
Iteration 19, inertia 721821347429.629.
Iteration 20, inertia 721378701557.364.
Iteration 21, inertia 720975652906.6685.
Iteration 22, inertia 720554534129.306.
Iteration 23, inertia 720191998770.8026.
Iteratio

In [57]:
print(silhouette_score(data_dryBean, km.labels_))

0.5324233773597118


#Question 13

What is the Rand index if you run k-means with k=7? Your answer must be correct up to two digits after the decimal point. You might have to run k-means many times to find the best result. (Remember, k-means is non-deterministic.)

In [58]:
def rand_index(result, gf):
  print(len(result))
  print(len(gf))
  count_matches = 0.0
  count_all = 0.0
  for i in range(len(result)):
    for j in range(i+1, len(gf)):
      if (result[i] == result[j] and gf[i] == gf[j]) or (result[i] != result[j] and gf[i] != gf[j]):
        count_matches += 1
      count_all += 1
  return count_matches / count_all

goldLabels = gld_labels
kLabels = km.labels_
print("Rand Index: ", rand_index(kLabels, goldLabels))

13611
13611
Rand Index:  0.7856400453214274
