<a href="https://colab.research.google.com/github/ucchol/docker/blob/main/Data_Mining_Homework_4_Page_Rank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from numpy import array
threshold= 0.0000000000000000001

In [ ]:
# fig 1
fig1 = [
    [1, 0, 1, 1, 1],
    [1, 0, 0, 0, 1],
    [0, 1, 1, 1, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 1, 1, 0]
    ]

In [ ]:
# fig 2
A = [
    [0, 0, 1, 1, 0],
    [1, 0, 0, 0, 1],
    [0, 1, 1, 1, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 1, 1, 1]
    ]

In [ ]:
# fig 3
A = [
    [1, 0, 0, 0, 1],
    [0, 0, 1, 1, 1],
    [0, 1, 1, 1, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 1, 0, 1]
    ]

In [ ]:
# fig 4
A = [
    [0, 0, 1, 0, 0],
    [1, 0, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 1, 0, 0],
    [0, 1, 0, 0, 1]
    ]

In [ ]:
# fig 5
A = [
    [0, 0, 0, 0, 1],
    [0, 1, 1, 1, 1],
    [0, 1, 0, 1, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 1, 0, 1]
    ]

QUESTION 2

Using the page rank algorithm without any teleportation, which node of Fig 1 has the least ranking score? That is which node is the least popular?

In [2]:
fig1 = [
    [1, 0, 1, 1, 1],
    [1, 0, 0, 0, 1],
    [0, 1, 1, 1, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 1, 1, 0]
    ]

In [3]:
arr= np.array(fig1, dtype=float)

s=[]
for i in range(0, len(fig1)):
  s.append(np.sum(arr[:, i]))

print("Summation of columns: ",s)

#now calculating M, column stochastic Matrix

M= arr
for j in range(0, len(fig1)):
  M[:,j]= M[:,j]/s[j]
  
print("Column of Stochastic Matrix, M:" )
print(M)

r= (1.0+ np.zeros([len(M), 1]))/ len(M)

print("Initial Rank Vector, r: ")
print(r)

Summation of columns:  [2.0, 1.0, 4.0, 3.0, 2.0]
Column of Stochastic Matrix, M:
[[0.5        0.         0.25       0.33333333 0.5       ]
 [0.5        0.         0.         0.         0.5       ]
 [0.         1.         0.25       0.33333333 0.        ]
 [0.         0.         0.25       0.         0.        ]
 [0.         0.         0.25       0.33333333 0.        ]]
Initial Rank Vector, r: 
[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]


In [4]:
#using while loop

r_prev= r


i=1
while(True):
  print("Interation: ",i)
  r= np.matmul(M, r_prev)
  print("The Rank Vector, r ")
  print(r)
  diff= np.sum(abs(r - r_prev)) #taking L1 norm
  if (diff< threshold):
    break

  r_prev= r 
  i+= 1

print("The final Rank Vector: ")
print(r[:,0])

Interation:  1
The Rank Vector, r 
[[0.31666667]
 [0.2       ]
 [0.31666667]
 [0.05      ]
 [0.11666667]]
Interation:  2
The Rank Vector, r 
[[0.3125    ]
 [0.21666667]
 [0.29583333]
 [0.07916667]
 [0.09583333]]
Interation:  3
The Rank Vector, r 
[[0.30451389]
 [0.20416667]
 [0.31701389]
 [0.07395833]
 [0.10034722]]
Interation:  4
The Rank Vector, r 
[[0.30633681]
 [0.20243056]
 [0.30807292]
 [0.07925347]
 [0.10390625]]
Interation:  5
The Rank Vector, r 
[[0.30855758]
 [0.20512153]
 [0.30586661]
 [0.07701823]
 [0.10343605]]
Interation:  6
The Rank Vector, r 
[[0.30813621]
 [0.20599682]
 [0.30726092]
 [0.07646665]
 [0.1021394 ]]
Interation:  7
The Rank Vector, r 
[[0.30744192]
 [0.2051378 ]
 [0.30830093]
 [0.07681523]
 [0.10230411]]
Interation:  8
The Rank Vector, r 
[[0.30755333]
 [0.20487302]
 [0.30781811]
 [0.07707523]
 [0.10268031]]
Interation:  9
The Rank Vector, r 
[[0.30776309]
 [0.20511682]
 [0.30751929]
 [0.07695453]
 [0.10264627]]
Interation:  10
The Rank Vector, r 
[[0.307736

QUESTION 4

Using the page rank algorithm without any teleportation, which node of Fig 3 is the most popular node?

		
A

		
B

		
C

		
D

		
E



In [ ]:
# fig 3
fig3 = [
    [1, 0, 0, 0, 1],
    [0, 0, 1, 1, 1],
    [0, 1, 1, 1, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 1, 0, 1]
    ]

arr= np.array(fig3, dtype=float)

s=[]
for i in range(0, len(fig3)):
  s.append(np.sum(arr[:, i]))

print("Summation of columns: ",s)

#now calculating M, column stochastic Matrix

M= arr
for j in range(0, len(fig3)):
  M[:,j]= M[:,j]/s[j]
  
print("Column of Stochastic Matrix, M:" )
print(M)

r= (1.0+ np.zeros([len(M), 1]))/ len(M)

print("Initial Rank Vector, r: ")
print(r)

Summation of columns:  [1.0, 1.0, 4.0, 2.0, 3.0]
Column of Stochastic Matrix, M:
[[1.         0.         0.         0.         0.33333333]
 [0.         0.         0.25       0.5        0.33333333]
 [0.         1.         0.25       0.5        0.        ]
 [0.         0.         0.25       0.         0.        ]
 [0.         0.         0.25       0.         0.33333333]]
Initial Rank Vector, r: 
[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]


In [ ]:
#using while loop

r_prev= r

i=1
while(True):
  print("Interation: ",i)
  r= np.matmul(M, r_prev)
  print("The Rank Vector, r ")
  print(r)
  diff= np.sum(abs(r - r_prev)) #taking L1 norm
  if (diff< threshold):
    break

  r_prev= r 
  i+= 1

print("The final Rank Vector: ")
print(r[:,0])

Interation:  1
The Rank Vector, r 
[[0.26666667]
 [0.21666667]
 [0.35      ]
 [0.05      ]
 [0.11666667]]
Interation:  2
The Rank Vector, r 
[[0.30555556]
 [0.15138889]
 [0.32916667]
 [0.0875    ]
 [0.12638889]]
Interation:  3
The Rank Vector, r 
[[0.34768519]
 [0.1681713 ]
 [0.27743056]
 [0.08229167]
 [0.1244213 ]]
Interation:  4
The Rank Vector, r 
[[0.38915895]
 [0.15197724]
 [0.27867477]
 [0.06935764]
 [0.1108314 ]]
Interation:  5
The Rank Vector, r 
[[0.42610275]
 [0.14129131]
 [0.25632475]
 [0.06966869]
 [0.10661249]]
Interation:  6
The Rank Vector, r 
[[0.46164025]
 [0.13445303]
 [0.24020685]
 [0.06408119]
 [0.09961869]]
Interation:  7
The Rank Vector, r 
[[0.49484648]
 [0.12529853]
 [0.22654534]
 [0.06005171]
 [0.09325794]]
Interation:  8
The Rank Vector, r 
[[0.52593246]
 [0.11774817]
 [0.21196072]
 [0.05663633]
 [0.08772231]]
Interation:  9
The Rank Vector, r 
[[0.55517323]
 [0.11054912]
 [0.19905652]
 [0.05299018]
 [0.08223095]]
Interation:  10
The Rank Vector, r 
[[0.582583

QUESTION 8

Using the page rank algorithm with random teleportation capacity using beta=0.5, which node of Fig 3 is the most popular node?

In [ ]:
beta= 0.5
uniformR= (1.0- beta)*r
r_prev= r

i=1
for i in range(1, 1001):
  print("Interation: ",i)
  r= beta*np.matmul(M, r_prev)+ uniformR
  print("The Rank Vector, r ")
  print(r)
  diff= np.sum(abs(r - r_prev)) #taking L1 norm
  if (diff< threshold):
    break

  r_prev= r 
  i+= 1

print("The final Rank Vector: ")
print(r[:,0])

Interation:  1
The Rank Vector, r 
[[0.11428571]
 [0.22857143]
 [0.34285714]
 [0.08571429]
 [0.22857143]]
The final Rank Vector: 
[0.11428571 0.22857143 0.34285714 0.08571429 0.22857143]


QUESTION 5

With beta=0.6 to enable random teleportation, what is the page rank score (probability) of the most popular node of Fig 2? Your answer must be correct up to four digits after the decimal point.

In [ ]:
fig2 = [
    [0, 0, 1, 1, 0],
    [1, 0, 0, 0, 1],
    [0, 1, 1, 1, 0],
    [0, 0, 1, 0, 0],
    [0, 0, 1, 1, 1]
    ]

arr= np.array(fig2, dtype=float)

s=[]
for i in range(0, len(fig2)):
  s.append(np.sum(arr[:, i]))

print("Summation of columns: ",s)

#now calculating M, column stochastic Matrix

M= arr
for j in range(0, len(fig2)):
  M[:,j]= M[:,j]/s[j]
  
print("Column of Stochastic Matrix, M:" )
print(M)

r= (1.0+ np.zeros([len(M), 1]))/ len(M)

print("Initial Rank Vector, r: ")
print(r)

Summation of columns:  [1.0, 1.0, 4.0, 3.0, 2.0]
Column of Stochastic Matrix, M:
[[0.         0.         0.25       0.33333333 0.        ]
 [1.         0.         0.         0.         0.5       ]
 [0.         1.         0.25       0.33333333 0.        ]
 [0.         0.         0.25       0.         0.        ]
 [0.         0.         0.25       0.33333333 0.5       ]]
Initial Rank Vector, r: 
[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]


In [ ]:
beta= 0.6
uniformR= (1.0- beta)*r
r_prev= r

i=1
for i in range(1, 1001):
  print("Interation: ",i)
  r= beta*np.matmul(M, r_prev)+ uniformR
  print("The Rank Vector, r ")
  print(r)
  diff= np.sum(abs(r - r_prev)) #taking L1 norm
  if (diff< threshold):
    break

  r_prev= r 
  i+= 1

print("The final Rank Vector: ")
print(r[:,0])

Streaming output truncated to the last 5000 lines.
Interation:  287
The Rank Vector, r 
[[0.11929437]
 [0.2319464 ]
 [0.33694373]
 [0.08961894]
 [0.22219656]]
Interation:  288
The Rank Vector, r 
[[0.11929437]
 [0.2319464 ]
 [0.33694373]
 [0.08961894]
 [0.22219656]]
Interation:  289
The Rank Vector, r 
[[0.11929437]
 [0.2319464 ]
 [0.33694373]
 [0.08961894]
 [0.22219656]]
Interation:  290
The Rank Vector, r 
[[0.11929437]
 [0.2319464 ]
 [0.33694373]
 [0.08961894]
 [0.22219656]]
Interation:  291
The Rank Vector, r 
[[0.11929437]
 [0.2319464 ]
 [0.33694373]
 [0.08961894]
 [0.22219656]]
Interation:  292
The Rank Vector, r 
[[0.11929437]
 [0.2319464 ]
 [0.33694373]
 [0.08961894]
 [0.22219656]]
Interation:  293
The Rank Vector, r 
[[0.11929437]
 [0.2319464 ]
 [0.33694373]
 [0.08961894]
 [0.22219656]]
Interation:  294
The Rank Vector, r 
[[0.11929437]
 [0.2319464 ]
 [0.33694373]
 [0.08961894]
 [0.22219656]]
Interation:  295
The Rank Vector, r 
[[0.11929437]
 [0.2319464 ]
 [0.33694373]
 [0.08

In [ ]:
#The final Rank Vector beta = 0.6: 
#[0.11929437 0.2319464  0.33694373 0.08961894 0.22219656]

#The final Rank Vector: 
#[0.11428571 0.22857143 0.34285714 0.08571429 0.22857143]

QUESTION 7

Let us consider that p(X, beta) gives the page rank probability score of node X of a network using beta to enable random teleportation. Which of the following statements is/are correct for nodes of Fig 2? Your answer must consider probabilities with no less than four digits after the decimal point.



		
p(A, 1.0)>p(A, 0.6)

		
p(E, 1.0)<p(D, 0.6)

		
p(E, 1.0)>p(E, 0.6)

		
p(B, 1.0)<p(E, 0.6)

		
p(D, 1.0)<p(D, 0.6)

beta= **1**

In [ ]:
beta= 1
uniformR= (1.0- beta)*r
r_prev= r

i=1
for i in range(1, 1001):
  print("Interation: ",i)
  r= beta*np.matmul(M, r_prev)+ uniformR
  print("The Rank Vector, r ")
  print(r)
  diff= np.sum(abs(r - r_prev)) #taking L1 norm
  if (diff< threshold):
    break

  r_prev= r 
  i+= 1

print("The final Rank Vector: ")
print(r[:,0])

Interation:  1
The Rank Vector, r 
[[0.11410891]
 [0.23039265]
 [0.34605531]
 [0.08423593]
 [0.22520719]]
Interation:  2
The Rank Vector, r 
[[0.11459247]
 [0.22671251]
 [0.34498512]
 [0.08651383]
 [0.22719607]]
Interation:  3
The Rank Vector, r 
[[0.11508422]
 [0.22819051]
 [0.34179673]
 [0.08624628]
 [0.22868226]]
Interation:  4
The Rank Vector, r 
[[0.11419794]
 [0.22942535]
 [0.34238845]
 [0.08544918]
 [0.22853907]]
Interation:  5
The Rank Vector, r 
[[0.11408017]
 [0.22846748]
 [0.34350552]
 [0.08559711]
 [0.22834971]]
Interation:  6
The Rank Vector, r 
[[0.11440875]
 [0.22825503]
 [0.34287623]
 [0.08587638]
 [0.22858361]]
Interation:  7
The Rank Vector, r 
[[0.11434452]
 [0.22870056]
 [0.34259955]
 [0.08571906]
 [0.22863632]]
Interation:  8
The Rank Vector, r 
[[0.11422291]
 [0.22866268]
 [0.34292346]
 [0.08564989]
 [0.22854107]]
Interation:  9
The Rank Vector, r 
[[0.11428083]
 [0.22849344]
 [0.34294351]
 [0.08573087]
 [0.22855136]]
Interation:  10
The Rank Vector, r 
[[0.114312

In [ ]:
#The final Rank Vector beta = 0.6: 
#[0.11929437 0.2319464  0.33694373 0.08961894 0.22219656]

#The final Rank Vector: 
#[0.11428571 0.22857143 0.34285714 0.08571429 0.22857143]

QUESTION 1

Let us say that p(X, beta) denotes the page rank probability score of a node X using beta to activate random teleportation. With random teleportation capacity using beta=0.5, which of the following statements is entirely correct for the nodes of Fig 4? Your answer must consider probabilities with four digits (without rounding) after the decimal point.

		
p(D, 0.5)>p(E, 0.5)>p(B, 0.5)>p(C, 0.5)>p(A, 0.5)

		
p(D, 0.5)>p(B, 0.5)>p(A, 0.5)>p(C, 0.5)>p(E, 0.5)

		
p(E, 0.5)>p(B, 0.5)>p(C, 0.5)>p(A, 0.5)=p(D, 0.5)

		
p(A, 0.5)>p(C, 0.5)>p(B, 0.5)>p(E, 0.5)>p(D, 0.5)

		
p(A, 0.5)>p(C, 0.5)>p(E, 0.5)>p(B, 0.5)>p(D, 0.5)

		
p(D, 0.5)>p(E, 0.5)>p(B, 0.5)>p(A, 0.5)>p(C, 0.5)

		
p(C, 0.5)>p(A, 0.5)>p(D, 0.5)>p(B, 0.5)>p(E, 0.5)

		
p(C, 0.5)>p(A, 0.5)>p(B, 0.5)>p(E, 0.5)>p(D, 0.5)


In [5]:
# fig 4
fig4 = [
    [0, 0, 1, 0, 0],
    [1, 0, 1, 1, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 1, 0, 0],
    [0, 1, 0, 0, 1]
    ]

arr= np.array(fig4, dtype=float)

s=[]
for i in range(0, len(fig4)):
  s.append(np.sum(arr[:, i]))

print("Summation of columns: ",s)

#now calculating M, column stochastic Matrix

M= arr
for j in range(0, len(fig4)):
  M[:,j]= M[:,j]/s[j]
  
print("Column of Stochastic Matrix, M:" )
print(M)

r= (1.0+ np.zeros([len(M), 1]))/ len(M)

print("Initial Rank Vector, r: ")
print(r)

Summation of columns:  [1.0, 2.0, 4.0, 2.0, 1.0]
Column of Stochastic Matrix, M:
[[0.   0.   0.25 0.   0.  ]
 [1.   0.   0.25 0.5  0.  ]
 [0.   0.5  0.25 0.5  0.  ]
 [0.   0.   0.25 0.   0.  ]
 [0.   0.5  0.   0.   1.  ]]
Initial Rank Vector, r: 
[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]


In [6]:
beta= 0.5
uniformR= (1.0- beta)*r
r_prev= r

i=1
for i in range(1, 1001):
  print("Interation: ",i)
  r= beta*np.matmul(M, r_prev)+ uniformR
  print("The Rank Vector, r ")
  print(r)
  diff= np.sum(abs(r - r_prev)) #taking L1 norm
  if (diff< threshold):
    break

  r_prev= r 
  i+= 1

print("The final Rank Vector: ")
print(r[:,0])

Interation:  1
The Rank Vector, r 
[[0.125]
 [0.275]
 [0.225]
 [0.125]
 [0.25 ]]
Interation:  2
The Rank Vector, r 
[[0.128125]
 [0.221875]
 [0.228125]
 [0.128125]
 [0.29375 ]]
Interation:  3
The Rank Vector, r 
[[0.12851563]
 [0.22460938]
 [0.21601562]
 [0.12851563]
 [0.30234375]]
Interation:  4
The Rank Vector, r 
[[0.12700195]
 [0.22338867]
 [0.2152832 ]
 [0.12700195]
 [0.30732422]]
Interation:  5
The Rank Vector, r 
[[0.1269104 ]
 [0.22216187]
 [0.21450806]
 [0.1269104 ]
 [0.30950928]]
Interation:  6
The Rank Vector, r 
[[0.12681351]
 [0.22199631]
 [0.21408157]
 [0.12681351]
 [0.3102951 ]]
Interation:  7
The Rank Vector, r 
[[0.1267602 ]
 [0.22187033]
 [0.21396265]
 [0.1267602 ]
 [0.31064663]]
Interation:  8
The Rank Vector, r 
[[0.12674533]
 [0.22181548]
 [0.21390296]
 [0.12674533]
 [0.3107909 ]]
Interation:  9
The Rank Vector, r 
[[0.12673787]
 [0.22179687]
 [0.21387807]
 [0.12673787]
 [0.31084932]]
Interation:  10
The Rank Vector, r 
[[0.12673476]
 [0.22178816]
 [0.21386844]
 [0

Here, A and D has the same value.