<a href="https://colab.research.google.com/github/ucchol/docker/blob/main/Data_Mining_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# K- Means Clustering

In [2]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score 
from sklearn.metrics import silhouette_samples 
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import DBSCAN

In [4]:
from google.colab import files
uploaded = files.upload()

Saving dry_beans_benchmarkclusters.csv to dry_beans_benchmarkclusters.csv
Saving dry_beans_data.csv to dry_beans_data.csv
Saving practicegoldset.csv to practicegoldset.csv
Saving practicedata.csv to practicedata.csv


In [5]:
prac_data = pd.read_csv('practicedata.csv')
prac_goldset = pd.read_csv('practicegoldset.csv', header=None)

In [6]:
prac_data.shape

(56, 5)

In [7]:
prac_goldset.shape

(56, 1)

In [8]:
prac_data.columns

Index(['f1', 'f2', 'f3', 'f4', 'f5'], dtype='object')

In [9]:
data = prac_data.values

In [10]:
#goldset

labels = prac_goldset.values
gld_labels = labels[:, 0] 
print(gld_labels.shape)
print(gld_labels)

(56,)
[1 2 2 1 3 1 1 3 2 2 2 2 2 2 3 1 1 1 3 3 3 1 1 2 2 1 2 3 2 3 2 1 1 1 1 2 3
 2 3 3 3 1 1 1 3 2 3 1 2 2 2 3 2 1 1 2]


In [11]:
k=3
km = KMeans(n_clusters=k, verbose=0).fit(data)

In [12]:
print("The clustering Assignments are: ")
print(km.labels_)

The clustering Assignments are: 
[0 1 0 0 2 0 0 2 1 1 1 1 1 1 2 0 0 0 2 2 2 0 0 1 1 0 1 2 1 2 1 0 0 0 0 1 2
 1 2 2 2 0 1 0 2 1 2 0 1 1 1 2 1 2 0 1]


With k= 3, using k-means clustering:

The number of rows/objects in the clusters is: 

Cluster 0 has 21 rows (that is, the size of Cluster 0 is 21)

Cluster 1 has 16 rows (that is, the size of Cluster 1 is 16)

Cluster 2 has 19 rows (that is, the size of Cluster 2 is 19)

In [13]:
unique, counts = np.unique(km.labels_, return_counts=True)
print(np.asarray((unique, counts)).T)

[[ 0 19]
 [ 1 21]
 [ 2 16]]


The sum of squared distances of samples/rows to their closest cluster center (inertia_) is 43.58434029761278.

In [14]:
print("SSD (sum of squared distance): ", km.inertia_)

SSD (sum of squared distance):  43.58434029761279


In [26]:
#Rand index is 0.9285714285714286.

def randIndex(result, gs):
  TP=0
  TN=0
  FP=0
  FN=0

  for i in range(0, len(result)-1):
    for j in range(i+1, len(result)):
      if(result[i]==result[j]):  #positive result
        if(gs[i]==gs[j]):
          TP = TP + 1
        else:
          FP = FP + 1

      else:
        if(gs[i]==gs[j]):
          FN = FN + 1
        else:
          TN = TN + 1

  RI= TP+TN/(TP+TN+FP+FN)
  return RI

print(randIndex(gld_labels, km.labels_ ))

448.63766233766233


In [16]:
#Purity is 0.9464285714285714.

def purity(result, gs):   #result and gs are labels
  cLabel= list(set(result)) # list will have the cluster labels
  gLabel= list(set(gs)) # list will have the ground_cluster truth labels , length of t from our equation
  n= len(result)
  k= len(cLabel)
  t= len(gLabel)

  #constructing dictionaries for cLable and glabel
  cLabelsD= dict(zip(cLabel, range(k))) #for clustering
  gLabelsD= dict(zip(gLabel, range(t))) #for ground truth

  clusterGroundDistr= [[0] * t for i in range(k)] #this will create a 2D array of t many columns and k many rows

  for i in range(n):  #number of elements we have is n
    clusterIndex = cLabelsD[result[i]]
    groundIndex = gLabelsD[gs[i]]
    clusterGroundDistr[clusterIndex][groundIndex] += 1

  p=0 # p is purity
  for i in range(k):
    p += max(clusterGroundDistr[i])

  return p/n

print(purity(gld_labels, km.labels_ ))

0.9464285714285714


In [17]:
#The average silhouette coefficient is 0.7870880067126674. 

print(silhouette_score(data, km.labels_))

0.7870880067126678


# Agglomerative clustering with three clusters: 

In [18]:
agg = AgglomerativeClustering(n_clusters=3).fit(data)
agg.labels_

array([1, 0, 1, 1, 2, 1, 1, 2, 0, 0, 0, 0, 0, 0, 2, 1, 1, 1, 2, 2, 2, 1,
       1, 0, 0, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 0, 2, 0, 2, 2, 2, 1, 0, 1,
       2, 0, 2, 1, 0, 0, 0, 2, 0, 2, 1, 0])

In [28]:
#Rand index using agglomerative clustering with three clusters is 0.9285714285714286.

print(randIndex(gld_labels, agg.labels_))

448.63766233766233


In [29]:
#Purity using Agglomerative clustering with three clusters is 0.9464285714285714.

print(purity(gld_labels, agg.labels_ ))

0.9464285714285714


# DBSCAN: 

In [30]:
dbres = DBSCAN(eps=1.0, min_samples=3).fit(data)
print(dbres.labels_)

[ 0  5  0  0  1  0  0  1  2  3 -1  4  5  2  1  0  0  0  1  1  1  0  0  3
  4  0  2  1  3  1 -1  0  0  0  0  4  1  2  1  1  1  0  5  0  1  2  1  0
  3  2  5  1  2  1  0  5]


In [31]:
dbres = DBSCAN(eps=1.0, min_samples=5).fit(data)
print(dbres.labels_)

[ 0 -1  0  0  1  0  0  1 -1 -1 -1 -1 -1 -1  1  0  0  0  1  1  1  0  0 -1
 -1  0 -1  1 -1  1 -1  0  0  0  0 -1  1 -1  1  1  1  0 -1  0  1 -1  1  0
 -1 -1 -1  1 -1  1  0 -1]


# HomeWork2/Assignment

In [32]:
dryBean_data = pd.read_csv('dry_beans_data.csv')
dryBean_goldset = pd.read_csv('dry_beans_benchmarkclusters.csv', header=None)

In [37]:
data_dryBean = dryBean_data.values

In [48]:
print("The clustering Assignments are: ")
print(km.labels_)

The clustering Assignments are: 
[3 0 5 ... 5 2 6]


In [38]:
labels = dryBean_goldset.values
gld_labels = labels[:, 0] 
print(gld_labels.shape)
print(gld_labels)

(13611,)
[5 7 1 ... 1 3 2]


In [39]:
agg = AgglomerativeClustering(n_clusters=7).fit(data_dryBean)
agg.labels_

array([0, 4, 1, ..., 1, 5, 0])

In [61]:
#purity agglomerative
print(purity(gld_labels, km.labels_))

0.6576298582029241


In [43]:
unique, counts = np.unique(agg.labels_, return_counts=True)
print(np.asarray((unique, counts)).T)

[[   0 2881]
 [   1 4939]
 [   2  335]
 [   3  979]
 [   4 3069]
 [   5  185]
 [   6 1223]]


In [42]:
print(randIndex(gld_labels, agg.labels_))

9378913.687151685


In [63]:
print(silhouette_score(data_dryBean, agg.labels_))

0.5050234057202192


In [45]:
k=7
km = KMeans(n_clusters=k, verbose=0).fit(data_dryBean)

In [49]:
unique, counts = np.unique(km.labels_, return_counts=True)
print(np.asarray((unique, counts)).T)

[[   0 3265]
 [   1 1148]
 [   2  217]
 [   3 2538]
 [   4  303]
 [   5 4226]
 [   6 1914]]


#Question 1

What is the average silhouette coefficient of the result retrieved by the agglomerative clustering algorithm with k=7? Your result must be correct up to two digits after the decimal point. Use default values with n_clusters=7 for scikitlearn AgglomerativeClustering. That is, do not mention any linkage in the parameters so that the default one is used.

#Question 7
How many data points are there in the dry beans dataset?



In [35]:
dryBean_data

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0       50833    898.973       362.353924       179.724613      2.016162   
1       30727    664.146       235.920043       167.045988      1.412306   
2       41324    733.765       261.771429       201.239402      1.300796   
3       25376    585.844       218.601389       148.020792      1.476829   
4      160273   1550.026       599.079539       343.574712      1.743666   
...       ...        ...              ...              ...           ...   
13606   83168   1154.625       400.255941       265.054216      1.510091   
13607  195106   1648.761       619.838810       404.009229      1.534219   
13608   36741    692.928       238.615411       196.465004      1.214544   
13609  191554   1682.544       635.396000       385.930852      1.646399   
13610   60409    946.447       359.752385       215.049972      1.672878   

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0          0.868327       51604     254.406340  0.809005  0.985059   0.790428   
1          0.706150       31212     197.794923  0.703441  0.984461   0.875393   
2          0.639537       41613     229.380363  0.790512  0.993055   0.964491   
3          0.735867       25642     179.749066  0.765999  0.989626   0.929114   
4          0.819203      163513     451.736562  0.808871  0.980185   0.838286   
...             ...         ...            ...       ...       ...        ...   
13606      0.749317       84772     325.411718  0.713362  0.981079   0.783942   
13607      0.758393      197343     498.414160  0.791049  0.988664   0.901914   
13608      0.567528       37052     216.287064  0.752643  0.991606   0.961578   
13609      0.794407      193468     493.856384  0.712505  0.990107   0.850292   
13610      0.801666       61368     277.335767  0.731415  0.984373   0.847459   

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  
0         0.702094      0.007128      0.001068      0.492935      0.993837  
1         0.838398      0.007678      0.002340      0.702911      0.992726  
2         0.876262      0.006335      0.002304      0.767835      0.998797  
3         0.822269      0.008614      0.002429      0.676126      0.998522  
4         0.754051      0.003738      0.000745      0.568593      0.991436  
...            ...           ...           ...           ...           ...  
13606     0.813009      0.004813      0.001297      0.660984      0.998146  
13607     0.804103      0.003177      0.000819      0.646581      0.991998  
13608     0.906425      0.006495      0.002704      0.821607      0.997878  
13609     0.777242      0.003317      0.000747      0.604105      0.994598  
13610     0.770907      0.005955      0.001297      0.594298      0.994188  

[13611 rows x 16 columns]

#Question 8
After applying k-means clustering with k=7, how many objects/data points are there in the smallest cluster?



In [57]:
unique, counts = np.unique(km.labels_, return_counts=True)
n= print(np.asarray((unique, counts)).T)

[[   0 3265]
 [   1 1148]
 [   2  217]
 [   3 2538]
 [   4  303]
 [   5 4226]
 [   6 1914]]



# Question 9
How many dimensional dataset is the Dry Beans dataset? (How many features are there in the dry_beans_data.csv file?) Just write an integer. 



In [34]:
dryBean_data.shape

(13611, 16)

# Question 10

Among three clustering algorihms -- kmeans, agglomerative, and DBSCAN -- which one(s) might give several different Rand Index values in multiple executions with the same data and parameters.

Why? Answer in one or two sentences.

The k-means clustering algorithm might give different Rand Index values in multiple executions with the same data and parameters because it is sensitive to the initial random selection of cluster centroids. The DBSCAN algorithm is less likely to produce different Rand Index values as it is based on density and does not rely on initializations, while the agglomerative clustering algorithm's behavior depends on the linkage criterion chosen.


#Question 11
What is the purity if you run agglomerative clustering with k=7? Your answer must be correct up to two digits after the decimal point. Use default values with n_clusters=7 for scikitlearn AgglomerativeClustering. That is, do not mention any linkage in the parameters so that the default one is used.

In [58]:
print(purity(gld_labels, agg.labels_ ))

0.6744544853427374


#Question 12

What is the average silhouette coefficient of the result retrieved by the k-means algorithm with k=7? Your result must be correct up to two digits after the decimal point. You might have to run k-means several times to find the best result. (Remember, k-means is non-deterministic.)

In [65]:
print(silhouette_score(data_dryBean, km.labels_))

0.532953088034952


#Question 13

What is the Rand index if you run k-means with k=7? Your answer must be correct up to two digits after the decimal point. You might have to run k-means many times to find the best result. (Remember, k-means is non-deterministic.)